---
id: Kolab_Format
name: Kolab_Format
full: Kolab data format library
description: A library that allows converting Kolab data objects from XML to data arrays.
list: dev
type: library
homepage: https://www.horde.org/libraries/Horde_Kolab_Format
authors:
  -
    name: Gunnar Wrobel
    user: wrobel
    email: p@rdus.de
    active: false
    role: lead
version:
  release: 2.0.10
  api: 2.0.0
state:
  release: stable
  api: stable
license:
  identifier: LGPL-2.1
  uri: http://www.horde.org/licenses/lgpl21
dependencies:
  required:
    php: ^5.3 || ^7
    pear:
      pear.horde.org/Horde_Exception: ^2
      pear.horde.org/Horde_Util: ^2
    ext:
      dom: '*'
  optional:
    pear:
      pear.horde.org/Horde_Support: ^2
      pear.horde.org/Horde_Test: ^2.1
    ext:
      mbstring: '*'
